name: fe_cinebox
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  dio: ^5.9.0
  envied: ^1.2.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.0-dev.17
  flutter_secure_storage: ^9.2.4
  google_sign_in: ^7.1.1
  json_annotation: ^4.9.0
  loading_animation_widget: ^1.3.0
  logger: ^2.6.1
  retrofit: ^4.7.2
  riverpod_annotation: ^3.0.0-dev.17

dev_dependencies:
  build_runner: ^2.7.1
  custom_lint: ^0.8.0
  envied_generator: ^1.2.1
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.11.0
  retrofit_generator: ^10.0.0
  riverpod_generator: ^3.0.0-dev.17
  riverpod_lint: ^3.0.0-dev.17

flutter:
  uses-material-design: true

  assets:
    - assets/images/
